### ISSUE TITLE
Alternative floor chair back model visuals

### ISSUE THREAD

**Issue by etzabo** [sudolev/CreateInteriorsMod#17]
The alternative seatback model used for floor chairs is mismatched in size with their default setting, and the texture becomes flipped on both axis. There's also a visible missing texture line on the kelp version.

Default model (no issues):
<img width="1680" alt="Screenshot 2024-06-18 at 20 14 49" src="https://github.com/aesefficio/CreateInteriorsMod/assets/101374457/4e8566e5-0f08-499d-82aa-c06bc5f88b72">
Alternative model (line is hard to see, but certainly there):
<img width="1680" alt="Screenshot 2024-06-18 at 20 16 51" src="https://github.com/aesefficio/CreateInteriorsMod/assets/101374457/349040e9-0b83-4dcf-9808-d4a8e927aaef">
Looking at the rear, you can see the size discrepancy in relation to the seat body of the chair. This discrepancy is not visible on the default model:
<img width="1680" alt="Screenshot 2024-06-18 at 20 18 17" src="https://github.com/aesefficio/CreateInteriorsMod/assets/101374457/b0bb2a0b-6f6e-4f52-a8a5-166079888ec5">

**Comment by a0ax** [comment]
Thanks for the issue!
That size discrepancy is there intentionally to prevent z fighting. I don't know that it's identical between the two models, but it's present in both. It's a bit larger than it would otherwise be for compatibility with embeddium, which reduces the resolution of models.
Probably not going to make any changes considering how minor of a problem this is
